(defun find-step-def ()
  (interactive)
  (let* ((line (thing-at-point 'line))
         (project-dir (projectile-project-root))
         (command (format "find-step-def.sh \"%s\" \"%s\"" project-dir line))
         (result (shell-command-to-string command))
         (parts (split-string result ":"))
         (filename (format "%s/%s" project-dir (nth 0 parts)))
         (lineno (string-to-number (string-trim (nth 1 parts)))))
    (goto-line lineno (find-file filename))
    (recenter)))

(defun index-step-defs()
  (interactive)
  (shell-command (format "/Users/gher33/bin/index-step-defs.sh \"%s\"" (projectile-project-root))))
